import { ExaminationPage } from '@/components/examination-page'

export const metadata = { title: 'IELTS Registration Support | Vertex Testing Services Limited', description: 'Professional IELTS registration support for education, migration, professional registration, and international opportunities.' }

export default function IELTSPage() {
  return <ExaminationPage title="IELTS – INTERNATIONAL ENGLISH LANGUAGE TESTING SYSTEM" intro="The International English Language Testing System (IELTS) is one of the world’s most widely recognized English language proficiency examinations. It is used by individuals seeking opportunities for international education, professional registration, employment, and migration. IELTS assesses Listening, Reading, Writing, and Speaking skills." sections={[
    { heading: 'IELTS TEST OPTIONS', paragraphs: ['IELTS Academic is designed primarily for candidates applying to universities, colleges, and other higher-education institutions, as well as for certain professional registration purposes.', 'IELTS General Training is commonly used for migration, employment, training, and other non-academic purposes, depending on the requirements of the relevant organization or immigration authority.', 'IELTS for UK Visas and Immigration (UKVI) is an approved Secure English Language Test for specific UK visa and immigration applications.', 'IELTS Life Skills assesses speaking and listening abilities for certain UK visa and immigration categories.'] },
    { heading: 'WHY TAKE IELTS?', paragraphs: ['IELTS results are accepted by thousands of educational institutions, professional organizations, employers, and government authorities internationally.'] , items: ['University and higher-education admission', 'International migration', 'Professional registration', 'Employment opportunities', 'Training and academic programmes', 'UK visa and immigration applications'] },
    { heading: 'IELTS REGISTRATION SUPPORT AT VERTEX', paragraphs: ['Vertex Testing Services Limited provides professional assistance to candidates who need support with their IELTS examination registration. Our team helps candidates understand test options, complete registration accurately, select suitable test dates and locations where available, and navigate the booking process with confidence.', 'Whether your goal is education, migration, professional development, or an international career, Vertex is ready to support your examination journey.'] }
  ]} />
}
